controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_qr:
    path: /v1/qr
    controller: App\Controller\QrCode::generate
    methods: POST
app_short_link_post:
    path: /v1/shortlink
    controller: App\Controller\ShortlinkController::generate
    methods: POST
app_short_link_redirect:
    path: /{link}
    controller: App\Controller\ShortlinkController::redirectShortLink
    methods: GET